# Local
prestoURL: "http://localhost:8080"
siteURLBase: "http://localhost:8889"
csvlocalPath: "/jetty/csv_temp"
logpath: "/jetty/logs"
# Hive
database: "presto_temp"
expiration: "7"
prestoCatalog: "hive"
hivepath: "/user/hive/warehouse"
deleteLogTTL: "30"
downloadToken: "a206379f7bffdcd01613869c448073ef98bfae8de4e17102b90f4758b2f316b7"
sqliteName: "Kado.sqlite"
presto_hdfs_user: "root"
wrtierinjection: "com.chickling.models.writer.LocalWriter"
