prestoURL: "http://172.16.157.11:8080"
database: "presto_temp"
hivepath: "/user/hive/warehouse"
logpath: "/jetty/logs"
siteURLBase: "http://localhost:8889"
expiration: "7"
prestoCatalog: "hive"
csvlocalPath: "/jetty/csv_temp"
deleteLogTTL: "30"
sqliteName: "Kado.sqlite"
wrtierinjection: "com.chickling.writer.DBWriter$com.chickling.models.writer.LocalWriter"
presto_hdfs_user: "root"
downloadToken: "a206379f7bffdcd01613869c448073ef98bfae8de4e17102b90f4758b2f316b7"

