prestoURL: "http://172.16.157.11:8080"
database: "presto_temp"
hivepath: "/user/hive/warehouse"
logpath: "D:\\Project\\Kado\\logs"
siteURLBase: "http://localhost:8889"
expiration: "7"
prestoCatalog: "hive"
csvtmphdfsPath: "/tmp/presto-csvtemp"
csvlocalPath: "D:\\kado_temp"
deleteLogTTL: "30"
sqliteName: "Kado.sqlite"
wrtierinjection: "com.chickling.writer.DBWriter$com.chickling.models.writer.LocalWriter"
saveLogToHDFS: "false"
presto_hdfs_user: "root"
# backup SQLite DB to HDFS
sqliteLOCALpath: "D:\\0_projects\\Kado\\src\\main\\resources\\Kado.sqlite"
sqliteHDFSpath: "/tmp"
#sqliteHDFSpath: "/user/ec/presto_backup"
downloadToken: "a206379f7bffdcd01613869c448073ef98bfae8de4e17102b90f4758b2f316b7"
