# Local
prestoURL: "http://localhost:8080"
siteURLBase: "http://localhost:8889"
csvlocalPath: "/home/user/presto_temp"
# HDFS  or Hive
database: "presto_temp"
hivepath: "/user/hive/warehouse"
logpath: "/tmp/presto-joblog"
expiration: "7"
prestoCatalog: "hive"
csvtmphdfsPath: "/tmp/presto-csvtemp"
deleteLogTTL: "30"

#   Scheduled
scheduleLogDir: "/logs/Schedule/"

# backup SQLite DB to HDFS
sqliteLOCALpath: "D:\\projects\\Kado\\src\\main\\resources\\Kado.sqlite"
sqliteName: "Kado.sqlite"
sqliteHDFSpath: "/tmp"
sqliteHDFSpath: "/user/ec/presto_backup"
wrtierinjection: "com.chickling.models.writer.HdfsWriter$com.chickling.models.writer.LocalWriter"

