prestoURL: "http://172.16.131.56:8080"
database: "presto_temp"
hivepath: "/user/hive/warehouse"
logpath: "/tmp/presto-joblog"
siteURLBase: "http://localhost:8889"
expiration: "7"
prestoCatalog: "hive"
csvtmphdfsPath: "/tmp/presto-csvtemp"
csvlocalPath: "/home/MERCURY/ecappservice/presto_temp"
deleteLogTTL: "30"
importBatchSize: "10000"
notbatchdb: "S7BIDB08"
sqliteName: "PrestoJobPortal.sqlite"
wrtierinjection: "com.chickling.writer.DBWriter$com.chickling.models.writer.HdfsWriter$com.chickling.models.writer.LocalWriter"
#
#   Scheduled
#
scheduleLogDir: "/logs/Schedule/"
#
# backup SQLite DB to HDFS
#
sqliteLOCALpath: "D:\\0_projects\\PrestoJobPortal\\src\\main\\resources\\PrestoJobPortal.sqlite"
sqliteHDFSpath: "/tmp"
#sqliteHDFSpath: "/user/ec/presto_backup"
# result output note
#
# 4 binary 100=HdfsWriter
# 2 binary 010=LocalWriter
# 1 binary 001=DBWriter
#